#!/usr/bin/env python3
"""Compares the live ue_ecmrs SQL columns and IDO properties with the target schema
(generate_schema_csv.py FIELDS) and writes docs/length-fixes.md - the changes to make in
Application Studio so that every column has its target type/length and every IDO property's
length equals its column's.

Inputs are the two Excel exports from TRN, saved as UTF-16 tab-separated files:
  docs/reference/ToExcel_SqlColumns_<date>.csv     (SQL Columns grid, table ue_ecmrs)
  docs/reference/ToExcel_IdoProperties_<date>.csv  (IDO Properties grid, IDO ue_ecmrs)
The newest dated pair is used. Re-export both after making the changes and re-run: both
tables in the output should be empty.

Run: python3 scripts/compare_live_lengths.py
"""
import csv
import glob
import io
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from generate_schema_csv import FIELDS, ORPHANED_COLUMNS

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REF = os.path.join(ROOT, "docs", "reference")
OUT = os.path.join(ROOT, "docs", "length-fixes.md")
TEXT_TYPES = {"nvarchar", "char", "varchar", "nchar"}

# Deliberately left as they are - explained in the generated file.
KEEP = {
    "cmr_num": "SQL is nvarchar(999), left over from the earlier type-change attempt; the IDO "
               "stays at 20. The key is a NumSortedString, which pads to its length for sorting. "
               "Don't change either side without testing on TRN.",
}
SYSTEM_IDO = {"CreatedBy": "128"}  # system property whose IDO length differs from SQL


def newest(pattern):
    files = sorted(glob.glob(os.path.join(REF, pattern)))
    if not files:
        raise SystemExit(f"no {pattern} in docs/reference")
    return files[-1]


def load(path):
    text = open(path, "rb").read().decode("utf-16")
    return list(csv.reader(io.StringIO(text), delimiter="\t"))


def num(v):
    return v.replace(",", "").strip()


def main():
    sql_path, ido_path = newest("ToExcel_SqlColumns_20*.csv"), newest("ToExcel_IdoProperties_20*.csv")
    sql_rows, ido_rows = load(sql_path), load(ido_path)
    sh, ih = sql_rows[0], ido_rows[0]
    sql = {r[sh.index("Column Name")]: r for r in sql_rows[1:] if len(r) > 5 and r[0]}
    ido = {r[ih.index("Column Name")]: r for r in ido_rows[1:] if len(r) > 12 and r[1]}

    sql_changes, ido_changes, notes, s_type_of = [], [], [], {}
    for (col, pname, dtype, length, _dec, coltype, *_rest) in FIELDS:
        s = sql.get(col)
        if s is None:
            notes.append(f"`{col}` is in the schema but not in the SQL export - check it exists.")
            continue
        s_type, s_sys = s[sh.index("Data Type")], s[sh.index("System Data Type")]
        s_len, s_def = num(s[sh.index("Length")]), s[sh.index("Default Value")]
        if s_sys not in TEXT_TYPES:
            continue
        if col in KEEP:
            notes.append(f"`{pname}` ({col}): {KEEP[col]}")
            continue
        if col in ORPHANED_COLUMNS:
            notes.append(f"`{col}` ({s_type}({s_len})) - not on the form; left as is.")
            continue
        want_type = coltype if coltype in TEXT_TYPES else s_type
        if coltype in TEXT_TYPES and s_len != length:
            sql_changes.append((col, f"{s_type}({s_len})", s_def, want_type, length))
            s_type_of[col] = s_type
        p = ido.get(col)
        if p is None:
            notes.append(f"`{col}` has no IDO property - add one ({pname}, String, {length}).")
            continue
        p_len = num(p[ih.index("*Length")])
        if p_len != length:
            ido_changes.append((pname, col, p_len, length))
    for col, s in sql.items():
        if col not in {f[0] for f in FIELDS} and col not in ido and s[sh.index("System Data Type")] in TEXT_TYPES:
            notes.append(f"`{col}` is a SQL column with no IDO property and not in the schema "
                         f"(stray duplicate?). Left as is.")
    for pname, want in SYSTEM_IDO.items():
        p = next((r for r in ido.values() if r[ih.index("Property Name")] == pname), None)
        if p and num(p[ih.index("*Length")]) != want:
            ido_changes.append((pname, pname, num(p[ih.index("*Length")]), want))

    L = ["# eCMRs — SQL column and IDO property lengths", "",
         "Generated by `scripts/compare_live_lengths.py` from the TRN exports "
         f"[`{os.path.basename(sql_path)}`](reference/{os.path.basename(sql_path)}) and "
         f"[`{os.path.basename(ido_path)}`](reference/{os.path.basename(ido_path)}), against the "
         "target schema in `scripts/generate_schema_csv.py`. Don't hand-edit: after the changes, "
         "export both grids again, save them here with the date, and re-run. Both tables should "
         "then be empty.", "",
         "**Target**: every text column we own is 255 long (`char(255)` on TRN) - generous, and "
         "still sortable and filterable in SyteLine grids (`nvarchar(max)` isn't everywhere). "
         "Columns using a SyteLine data type (`ItemType`, `DeptType`, `WcType`, `EmpNumType`, "
         "`UsernameType`, `DescriptionType`, `LongDescType`, `RevisionType`, `QCLongCharType`, "
         "`QCPriorityType`) keep that type's length: their values come from SyteLine and always "
         "fit. Every IDO property's **Length** equals its column's.", ""]
    L += ["## 1. SQL Columns (Application Studio → SQL Tables → `ue_ecmrs` → SQL Columns)", ""]
    if sql_changes:
        L += ["For each row: set **Length** to the value shown and save. If a row has a "
              "**Default Value**, clear it and save *first* - a column default blocks the change "
              "(the same *default-constraint* error `cmr_num` hit).", "",
              "| Column | Now | Default Value now | Set to |", "|---|---|---|---|"]
        for col, now, dflt, want_type, length in sql_changes:
            d = f"`{dflt}` → **clear first**" if dflt.strip() else ""
            L.append(f"| `{col}` | {now} | {d} | **{s_type_of[col]}({length})** |")
        L += ["", f"{len(sql_changes)} column(s). Values already stored are kept. If Application "
              "Studio refuses a change, stop and send the error.", ""]
    else:
        L += ["Nothing to change.", ""]
    L += ["## 2. IDO Properties (`ue_ecmrs`)", ""]
    if ido_changes:
        L += ["Set **Length**, then **Check In** the IDO and reopen the form. Do this after step 1.", "",
              "| Property | Column | Length now | Set to |", "|---|---|---|---|"]
        for pname, col, now, want in ido_changes:
            L.append(f"| `{pname}` | `{col}` | {now or '(blank)'} | **{want}** |")
        L += ["", f"{len(ido_changes)} properties. `CreatedBy` is a system property: if the grid "
              "won't let you change it, leave it.", ""]
    else:
        L += ["Nothing to change.", ""]
    if notes:
        L += ["## Left as is", ""] + [f"- {n}" for n in notes] + [""]
    with open(OUT, "w", newline="\n") as fh:
        fh.write("\n".join(L))
    print(f"Wrote docs/length-fixes.md: {len(sql_changes)} SQL change(s), {len(ido_changes)} IDO change(s)")


if __name__ == "__main__":
    main()
