#!/usr/bin/env python3
"""Compares the live SQL column lengths with the live IDO property lengths and with this repo's
schema (generate_schema_csv.py FIELDS), and writes docs/length-fixes.md - the list of fixes to
make in Application Studio.

Inputs are the two Excel exports from TRN, saved as UTF-16 tab-separated files:
  docs/reference/ToExcel_SqlColumns_<date>.csv     (SQL Columns grid, table ue_ecmrs)
  docs/reference/ToExcel_IdoProperties_<date>.csv  (IDO Properties grid, IDO ue_ecmrs)
The newest dated pair is used. Rule: the IDO property length must equal the SQL column length.

Run: python3 scripts/compare_live_lengths.py   (exit 1 if FIELDS disagrees with SQL)
"""
import csv
import glob
import io
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from generate_schema_csv import FIELDS

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REF = os.path.join(ROOT, "docs", "reference")
OUT = os.path.join(ROOT, "docs", "length-fixes.md")
TEXT_TYPES = {"nvarchar", "char", "varchar", "nchar"}

# The SQL column itself is wrong: fix it in the SQL Columns grid to this length (and the IDO
# property to match). cause_code came out as char(1) with Default Value "(100)" - the 100 was
# typed into Default Value instead of Length. Cause codes are up to 8 characters; 100 matches
# reason_code.
SQL_FIXES = {"cause_code": "100"}
# Deliberately not matched to SQL - see the note in the generated file.
IDO_KEEP = {
    "cmr_num": "SQL says nvarchar(999), left over from the earlier type-change attempt. The key is "
               "a NumSortedString, which pads to its length for sorting, so the IDO stays at 20 "
               "(CMR numbers are short). Don't change either side without testing on TRN.",
}
SYSTEM = {"CreatedBy", "UpdatedBy", "CreateDate", "RecordDate", "RowPointer", "NoteExistsFlag", "InWorkflow"}


def newest(pattern):
    files = sorted(glob.glob(os.path.join(REF, pattern)))
    if not files:
        raise SystemExit(f"no {pattern} in docs/reference")
    return files[-1]


def load(path):
    text = open(path, "rb").read().decode("utf-16")
    return list(csv.reader(io.StringIO(text), delimiter="\t"))


def num(v):
    return v.replace(",", "").strip()


def main():
    sql_path = newest("ToExcel_SqlColumns_20*.csv")
    ido_path = newest("ToExcel_IdoProperties_20*.csv")
    sql_rows, ido_rows = load(sql_path), load(ido_path)
    sh, ih = sql_rows[0], ido_rows[0]
    sql = {r[sh.index("Column Name")]: r for r in sql_rows[1:] if len(r) > 5 and r[0]}
    ido = {r[ih.index("Column Name")]: r for r in ido_rows[1:] if len(r) > 12 and r[1]}
    repo = {f[0]: f for f in FIELDS}

    ido_fixes, sql_fixes, notes, repo_bad = [], [], [], []
    for col, r in sql.items():
        stype, slen = r[sh.index("System Data Type")], num(r[sh.index("Length")])
        if stype not in TEXT_TYPES:
            continue
        p = ido.get(col)
        if p is None:
            notes.append(f"`{col}` is a SQL column with no IDO property (not on the form). "
                         f"Leave it; remove it only if nothing uses it.")
            continue
        pname, plen = p[ih.index("Property Name")], num(p[ih.index("*Length")])
        target = SQL_FIXES.get(col, slen)
        if col in SQL_FIXES:
            sql_fixes.append((col, stype, slen, r[sh.index("Default Value")], target))
        if col in IDO_KEEP:
            notes.append(f"`{pname}` ({col}): IDO {plen}, SQL {slen} - {IDO_KEEP[col]}")
            continue
        if plen != target:
            ido_fixes.append((pname, col, plen, target))
        if col in repo and col not in SYSTEM and repo[col][3] != target:
            repo_bad.append((col, repo[col][3], target))

    L = ["# eCMRs — IDO property lengths vs SQL columns", "",
         "Generated by `scripts/compare_live_lengths.py` from the TRN exports "
         f"[`{os.path.basename(sql_path)}`](reference/{os.path.basename(sql_path)}) and "
         f"[`{os.path.basename(ido_path)}`](reference/{os.path.basename(ido_path)}). Don't "
         "hand-edit; re-export both grids after fixing and re-run.", "",
         "Rule: each IDO property's **Length** must equal its SQL column's **Length**. A longer IDO "
         "length lets a value through the form that SQL then rejects (*\"String or binary data "
         "would be truncated\"*); a shorter one rejects valid values (*\"Data length ... is greater "
         "than effective length\"*).", ""]
    if sql_fixes:
        L += ["## 1. Fix the SQL column first (Application Studio → SQL Columns, table `ue_ecmrs`)", "",
              "| Column | Now | Default Value now | Set Length to | Set Default Value to |",
              "|---|---|---|---|---|"]
        for col, stype, slen, dflt, target in sql_fixes:
            L.append(f"| `{col}` | {stype}({slen}) | `{dflt}` | **{target}** | blank |")
        L += ["", "Do it in two saves: **1)** clear Default Value and save; **2)** set Length and save. "
              "A column default blocks the length change (same *default-constraint dependency* error "
              "`cmr_num` hit - see troubleshooting). Values already stored are at most 1 character, "
              "so nothing is lost. If Application Studio still refuses, stop and send the error.", ""]
    L += [f"## {2 if sql_fixes else 1}. Set these IDO property lengths (IDO Properties grid, `ue_ecmrs`)", "",
          "Then **Check In** the IDO, and reopen the form.", "",
          "| Property | Column | IDO Length now | Set to |", "|---|---|---|---|"]
    for pname, col, plen, target in ido_fixes:
        L.append(f"| `{pname}` | `{col}` | {plen or '(blank)'} | **{target}** |")
    L += ["", f"{len(ido_fixes)} properties. `CreatedBy` is a system property: if the grid won't "
          "let you change it, leave it (its SQL column is 128 and the system fills it).", ""]
    if notes:
        L += ["## Left as is", ""] + [f"- {n}" for n in notes] + [""]
    with open(OUT, "w", newline="\n") as fh:
        fh.write("\n".join(L))
    print(f"Wrote docs/length-fixes.md: {len(sql_fixes)} SQL fix(es), {len(ido_fixes)} IDO fix(es)")
    if repo_bad:
        print("FIELDS disagrees with SQL:", repo_bad)
        sys.exit(1)


if __name__ == "__main__":
    main()
