#!/usr/bin/env python3
"""Builds the production import files for the ue_ecmrs table and IDO from the final, working
TRN exports, and checks production against TRN after the build.

Why from the TRN exports: TRN is the version that is confirmed working. The Application Studio
grids import the same format they export (UTF-16, tab-separated, same header and quoting), so
the TRN export rows - minus the columns Application Studio creates by itself - are exactly
what production needs. Nothing is re-typed or re-generated.

Inputs (newest dated pair in docs/reference/):
  ToExcel_SqlColumns_<date>.csv     SQL Columns grid for table ue_ecmrs on TRN
  ToExcel_IdoProperties_<date>.csv  IDO Properties grid for IDO ue_ecmrs on TRN
Outputs:
  exports/production/ue_ecmrs_SqlColumns_import.csv
  exports/production/ue_ecmrs_IdoProperties_import.csv
  docs/production-build-sheet.md    every column and property, for checking by eye

Run:
  python3 scripts/make_production_imports.py            write the files
  python3 scripts/make_production_imports.py --check    fail if the committed files are stale
  python3 scripts/make_production_imports.py --verify <prod SqlColumns export> <prod IdoProperties export>
      compare production (after the build) with TRN: every column and property must match
"""
import csv
import glob
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REF = os.path.join(ROOT, "docs", "reference")
OUT_DIR = os.path.join(ROOT, "exports", "production")
SQL_OUT = os.path.join(OUT_DIR, "ue_ecmrs_SqlColumns_import.csv")
IDO_OUT = os.path.join(OUT_DIR, "ue_ecmrs_IdoProperties_import.csv")
SHEET = os.path.join(ROOT, "docs", "production-build-sheet.md")

# Created by Application Studio with every new table / IDO - never import these.
SYSTEM = {"CreatedBy", "UpdatedBy", "CreateDate", "RecordDate", "RowPointer", "NoteExistsFlag", "InWorkflow"}
# On TRN only, not part of the design: a stray duplicate of reported_by with no IDO property.
SKIP = {"ue_reported_by"}
# Compared by --verify. Column Id / Sequence / DevelopmentFlagGridCol can differ harmlessly.
SQL_KEYS = ["Data Type", "System Data Type", "Length", "Decimal Position", "Default Value",
            "Is Nullable", "Primary Key", "Key Sequence"]
IDO_KEYS = ["Property Name", "Property Class", "Column Table Alias", "Table Name", "Property Type",
            "Pseudo Key", "*Data Type", "*Length", "Default Value", "*Column Data Type",
            "Inline List", "Validators", "Required", "Read Only Record", "*Read Only"]


def newest(pattern):
    files = sorted(glob.glob(os.path.join(REF, pattern)))
    if not files:
        raise SystemExit(f"no {pattern} in docs/reference")
    return files[-1]


def read_lines(path):
    raw = open(path, "rb").read()
    if not raw.startswith(b"\xff\xfe"):
        raise SystemExit(f"{path}: expected a UTF-16 export (starts with FF FE)")
    return raw[2:].decode("utf-16-le").split("\r\n")


def parse(lines):
    rows = list(csv.reader(io.StringIO("\n".join(lines)), delimiter="\t"))
    return rows[0], [r for r in rows[1:] if len(r) > 5]


def keep(lines, name_col):
    """Header + data lines, dropping system and skipped rows; lines stay byte-for-byte."""
    header, out = lines[0], [lines[0]]
    hdr = next(csv.reader([header], delimiter="\t"))
    idx = hdr.index(name_col)
    for line in lines[1:]:
        if not line.strip():
            continue
        name = next(csv.reader([line], delimiter="\t"))[idx]
        if name in SYSTEM or name in SKIP:
            continue
        out.append(line)
    return out


def encode(lines):
    return b"\xff\xfe" + ("\r\n".join(lines) + "\r\n").encode("utf-16-le")


def build():
    sql_src, ido_src = newest("ToExcel_SqlColumns_20*.csv"), newest("ToExcel_IdoProperties_20*.csv")
    sql_lines = keep(read_lines(sql_src), "Column Name")
    ido_lines = keep(read_lines(ido_src), "Column Name")
    sh, srows = parse(sql_lines)
    ih, irows = parse(ido_lines)
    s = lambda r, k: r[sh.index(k)]
    p = lambda r, k: r[ih.index(k)]

    L = ["# eCMRs — production build sheet", "",
         "Generated by `scripts/make_production_imports.py` from the final TRN exports "
         f"[`{os.path.basename(sql_src)}`](reference/{os.path.basename(sql_src)}) and "
         f"[`{os.path.basename(ido_src)}`](reference/{os.path.basename(ido_src)}). Don't hand-edit.", "",
         "This is exactly what is working on TRN. The two import files in "
         "[`../exports/production/`](../exports/production/) hold the same rows in the grids' own "
         "format. Use this sheet to check the result by eye, or to key a row in by hand if an "
         "import row is rejected. Step by step: [`Implementation-Plan.md`](Implementation-Plan.md), "
         "phase 5 (Launch).", "",
         f"Not imported (Application Studio creates them with the table/IDO): "
         f"{', '.join('`%s`' % n for n in sorted(SYSTEM))}. Not built: `ue_reported_by` (stray on TRN).", "",
         f"## SQL Columns — table `ue_ecmrs` ({len(srows)} columns)", "",
         "| # | Column | Data Type | System type | Length | Default | Nullable | Key |",
         "|---|---|---|---|---|---|---|---|"]
    for i, r in enumerate(srows, 1):
        key = "**PK**" if s(r, "Primary Key") == "1" else ""
        L.append(f"| {i} | `{s(r, 'Column Name')}` | {s(r, 'Data Type')} | {s(r, 'System Data Type')} | "
                 f"{s(r, 'Length')} | {s(r, 'Default Value')} | {s(r, 'Is Nullable')} | {key} |")
    L += ["", f"## IDO Properties — IDO `ue_ecmrs`, table alias `ec` ({len(irows)} properties)", "",
          "| # | Property | Column | Data Type | Length | Inline List | Read Only Record | Default |",
          "|---|---|---|---|---|---|---|---|"]
    for i, r in enumerate(irows, 1):
        il = p(r, "Inline List")
        L.append(f"| {i} | `{p(r, 'Property Name')}` | `{p(r, 'Column Name')}` | {p(r, '*Data Type')} | "
                 f"{p(r, '*Length')} | {('`' + il + '`') if il else ''} | {p(r, 'Read Only Record')} | "
                 f"{p(r, 'Default Value')} |")
    L += ["", "Every Property Class is blank. `CmrNum`: String, no Default Value - the form sets "
          "`CMR-YYMMDD-HHMMSS` on **New**.", ""]
    return {SQL_OUT: encode(sql_lines), IDO_OUT: encode(ido_lines),
            SHEET: ("\n".join(L)).encode("utf-8")}, len(srows), len(irows)


def verify(prod_sql, prod_ido):
    trn_sql, trn_ido = newest("ToExcel_SqlColumns_20*.csv"), newest("ToExcel_IdoProperties_20*.csv")
    problems = []
    for label, trn, prod, name, keys in [
            ("SQL column", trn_sql, prod_sql, "Column Name", SQL_KEYS),
            ("IDO property", trn_ido, prod_ido, "Column Name", IDO_KEYS)]:
        th, tr = parse(keep(read_lines(trn), name))
        ph, pr = parse(keep(read_lines(prod), name))
        t = {r[th.index(name)]: r for r in tr}
        p = {r[ph.index(name)]: r for r in pr}
        for n in t:
            if n not in p:
                problems.append(f"{label} `{n}`: missing in production")
                continue
            for k in keys:
                a, b = t[n][th.index(k)], p[n][ph.index(k)]
                if a.replace(",", "") != b.replace(",", ""):
                    problems.append(f"{label} `{n}`: {k} is `{b}` in production, `{a}` on TRN")
        for n in p:
            if n not in t:
                problems.append(f"{label} `{n}`: in production but not on TRN")
    if problems:
        print("\n".join(problems))
        raise SystemExit(f"{len(problems)} difference(s) - fix them in Application Studio, Check In, re-export")
    print("OK: production matches TRN (every SQL column and IDO property)")


def main():
    if "--verify" in sys.argv:
        i = sys.argv.index("--verify")
        verify(sys.argv[i + 1], sys.argv[i + 2])
        return
    files, ns, ni = build()
    if "--check" in sys.argv:
        stale = [os.path.relpath(f, ROOT) for f, data in files.items()
                 if not os.path.exists(f) or open(f, "rb").read() != data]
        if stale:
            raise SystemExit(f"out of date: {', '.join(stale)} - re-run without --check")
        print("OK: production import files and build sheet are up to date")
        return
    os.makedirs(OUT_DIR, exist_ok=True)
    for f, data in files.items():
        with open(f, "wb") as fh:
            fh.write(data)
    print(f"Wrote {ns} SQL columns and {ni} IDO properties to exports/production/, "
          f"and docs/production-build-sheet.md")


if __name__ == "__main__":
    main()
