"""Updated quality procedures for the eCMRs form, shown in the help pages (docs/help/procedures/).

Source: the released procedures (copies in docs/reference/procedures/):
  QA-300-037 Rev A (7/7/2026)  MRR, CMR, and TRR Processing
  QA-300-003 Rev E (07/07/2026) Supplier Deviation Request (SDR)
The text is kept word for word; only what the eCMRs form changes is changed. Each changed or
removed step carries the original wording ("was") and the reason ("why"), so the team can review
the draft before it is released. Nothing here is approved - revisions are drafts.

Step tuple: (number, text, kind, was, why) - kind "" = unchanged, "changed", "removed", "added".
Section entry: ("h", "5.5. CMR Processing") for a heading.
"""

NOTICE = [
    "A hard copy of this document may not be the document currently in effect. The current version "
    "is always the version located and accessed on the designated secure shared file folder, "
    "“Released QMS Documents”.",
]

QA_300_037 = dict(
    key="qa-300-037",
    number="QA-300-037",
    title="MRR, CMR, and TRR Processing",
    rev_old="A", issued_old="7/7/2026",
    rev_new="B (draft)",
    summary="Section 5.5 (CMR Processing) and the CMR definition are updated for the eCMRs form. "
            "MRR (5.3) and TRR (5.4) processing are unchanged.",
    company_private=True,
    revlog=[
        ("A", "Original Release", "07/07/26", "K. Montgomery", "E. Laney", "J Nabe", "N/A"),
        ("B", "Updated CMR definition and section 5.5 CMR Processing for the eCMRs form (replaces "
              "Create Change Request, Change Request Management and QC CMRs).", "Draft", "", "", "", ""),
    ],
    scope="This procedure applies to Enflite personnel responsible for the disposition, use, and "
          "management of the MRR, CMR, and TRR forms within Syteline.",
    purpose="To establish a standardized procedure and process flow for processing MRR’s, CMR’s, "
            "and TRR’s in Syteline.",
    references=[
        ("QA 300-008", "Receiving Inspection"),
        ("QA 300-010", "Material Review Board"),
        ("QA 300-029", "Material Review"),
        ("QA 300-066", "Streamlined Rework Nonconformance Process"),
        ("QA 300-003", "Supplier Deviation Request"),
        ("ENG 310-005", "Engineering Orders – Policy, Process and Work Instruction"),
    ],
    definitions=[
        ("MRR", "Material Review Report;  a Syteline quality control form used to manage nonconforming, "
                "suspected, or damaged materials, including documentation, review, and disposition (e.g., "
                "scrap, rework, return to vendor).", "", "", ""),
        ("CMR", "Change Management Request; the “eCMRs” Syteline form used to manage deviations, "
                "clarifications, and process gaps identified by vendors, customers, and Enflite internal "
                "personnel. It replaces the Create Change Request, Change Request Management and QC CMRs "
                "forms.", "changed",
         "Change Management Request; A specialized Syteline quality control form used to manage "
         "deviations, clarifications, and process gaps identified by vendors, customers, and Enflite "
         "internal personnel.",
         "CMRs are now one form, eCMRs."),
        ("TRR", "Topic Review Request; A specialized Syteline quality control form used to track and manage "
                "errors by Enflite production personnel.", "", "", ""),
        ("Streamline", "Does not require detailed rework instructions or Engineering Disposition to return to "
                       "type design.  (e.g. Loose screws, missing washer, etc.)", "", "", ""),
        ("Syteline", "The Enflite ERP system used to manage end-to-end business operations.", "", "", ""),
        ("ECO", "Engineering Change Order: Used to explain changes to manufacturing documents.", "", "", ""),
        ("NEI", "Notice of Engineering Intent: Used to make minor changes to drawings to provide clarity or "
                "to address a discrepancy.", "", "", ""),
        ("TS", "Temporary Solution: Used to make minor temporary changes to a specific article or articles "
               "and provide valid acceptance.", "", "", ""),
    ],
    procedure=[
        ("h", "5.1. General Requirements"),
        ("5.1.1.", "All nonconformances, discrepancies, issues, deviations, clarifications, and process gaps "
                   "will be documented in the applicable form outlined by the requirements of this procedure. "
                   "Anything not defined in the process will be brought to the attention of the Quality "
                   "Manager (or Designee).", "", "", ""),
        ("h", "5.2. Problem identification and verification"),
        ("5.2.1.", "For In-process discrepancy, a PIR will be generated by the Production Tech using PIR "
                   "template, describing the issue along with pertinent details of part in question and job "
                   "order.", "", "", ""),
        ("5.2.2.", "Quality will review and verify reported issue on the production floor prior to initiation "
                   "of discrepancy in Syteline.", "", "", ""),
        ("5.2.3.", "Quality will determine if this PIR will be an MRR, CMR or TRR", "", "", ""),
        ("5.2.3.1.", "For issues that will include material transactions within Syteline, go to section 5.3 "
                     "MMR Processing.", "", "", ""),
        ("5.2.3.2.", "For issues that does not require detailed rework instructions or Engineering Disposition "
                     "to return to type design, go to section 5.4 TRR (Streamline) Processing.", "", "", ""),
        ("5.2.3.3.", "For issues that does not include material transactions, or to capture issues from the "
                     "supplier (such as a SDR) go to section 5.5 CMR Processing.", "", "", ""),
        ("h", "5.3. MRR Processing"),
        ("5.3.1.", "Trace the affected part back to its original “Supplier Inspect/ Disposition” receiver. If "
                   "the issue was identified during receiving inspection, proceed to Step 5.3.4. Otherwise, go "
                   "to Step 5.3.2", "", "", ""),
        ("5.3.2.", "If the MRR is being created outside of the receiving inspection, open the “Supplier "
                   "Inspect/Disposition” form and filter by the part’s lot number. Use the “IP Job "
                   "Inspect/Disposition” form if the part was manufactured at Enflite. If the lot number is "
                   "unavailable, locate it via the “Material Transactions” form and filtering by the affected "
                   "part number and job number.", "", "", ""),
        ("5.3.3.", "If the part is associated with an IP Job, contact planning to open the job operation: "
                   "otherwise, proceed to 5.3.4.", "", "", ""),
        ("5.3.3.1.", "Planning will open the applicable job operation used by the inspector and when complete "
                     "will notify QC Inspector the job operation is open.", "", "", ""),
        ("5.3.4.", "Select “Disposition QC Receiver”.", "", "", ""),
        ("5.3.5.", "Enter the affected quantity in the QC MRR/Hold section of the Disposition Receiving form "
                   "and input the appropriate reason code.", "", "", ""),
        ("5.3.6.", "Click “Process”, then click “OK” on the pop-up.", "", "", ""),
        ("5.3.7.", "Close the Qc Tags Report tab after making note of the MRR number.", "", "", ""),
        ("5.3.8.", "On the Syteline tab, click “OK” to confirm MRR creation.", "", "", ""),
        ("5.3.9.", "Click “OK” to confirm the quantity move.", "", "", ""),
        ("5.3.10.", "Verify the “to location” is correct, then click “Process.” If prompted that the location "
                    "does not exist, click “OK” to add it.", "", "", ""),
        ("5.3.11.", "When prompted “[Quantity Move] was successful,” click “OK.” If the prompt does not appear, "
                    "notify Quality Leadership.", "", "", ""),
        ("5.3.12.", "Open the MRR form using the part number and MRR number recorded in Step 5.3.7.", "", "", ""),
        ("5.3.13.", "Enter a clear problem description in the designated block. If created from an IP Job, "
                    "include at minimum: job number, top-level part number, affected part number, lot number, "
                    "and issue. Always state what the part should be versus what it is (e.g., “Part should be "
                    "3.00 ± 0.010 inches; part is 2.75 inches”). Include Sheet number and zone if applicable.",
         "", "", ""),
        ("5.3.14.", "Select the appropriate cause code from the drop-down menu.", "", "", ""),
        ("5.3.15.", "If the cause of defect is known, document it in the designated field.", "", "", ""),
        ("5.3.16.", "In the “Assigned To” field, select the appropriate party. If the issue is related to "
                    "tooling or measurement capability, assign to the Quality Manager or designee; otherwise, "
                    "assign to Engineering.", "", "", ""),
        ("5.3.17.", "If priority is required for processing, change Priority Field to one of the following "
                    "(based on need by date)", "", "", ""),
        ("5.3.17.1.", "Priority 1, High.  Select if ships or needs that day.", "", "", ""),
        ("5.3.17.2.", "Priority 2, Medium.  Select if ships or needed within 24 hours.", "", "", ""),
        ("5.3.17.3.", "Priority 3 Low (default), for all others.  Expected processing time within the week.",
         "", "", ""),
        ("5.3.18.", "Save the form.", "", "", ""),
        ("5.3.19.", "On Build Record, enter the MRR number for traceability within the Notes section at the end.",
         "", "", ""),
        ("5.3.20.", "Engineering/Quality reviews the issue and documents remarks in the Correction/Containment "
                    "block, including initials and date.", "", "", ""),
        ("5.3.21.", "Engineering finalizes disposition in the Correction/Containment block, saves supporting "
                    "documentation within IDM and reassigns the MRR to Planning/Purchasing. If an NEI or TS is "
                    "used, it must first be approved by the Quality.", "", "", ""),
        ("5.3.22.", "Planning and Purchasing review the MRR. Planning enters disposition in the "
                    "Correction/Containment block and shall not authorize rework or use-as-is if it conflicts "
                    "with Engineering’s disposition.", "", "", ""),
        ("5.3.23.", "Planning/Purchasing reassigns the MRR to the originating Quality Inspector.", "", "", ""),
        ("5.3.24.", "The Quality Inspector reviews all information for accuracy.", "", "", ""),
        ("5.3.25.", "The Quality Inspector dispositions the MRR per instructions from Planning, Engineering, or "
                    "Quality Manager.", "", "", ""),
        ("5.3.26.", "To disposition, click “Disposition MRR” and enter applicable information. If the part is to "
                    "be returned to stock, complete the “Accepted” section; otherwise, complete the “Rejected” "
                    "section.", "", "", ""),
        ("5.3.27.", "When accepting, always disposition as “MTS – Move to Stock,” then click “Process.”",
         "", "", ""),
        ("5.3.28.", "Print the QC Tags Report that appears, then close the tab.", "", "", ""),
        ("5.3.29.", "Click “OK” on the “Disposition Completed” pop-up. If it does not appear, contact Quality "
                    "Leadership.", "", "", ""),
        ("5.3.30.", "Click “OK” two additional times.", "", "", ""),
        ("5.3.31.", "Select the appropriate destination location. For RTV, enter “QC RTV.” Otherwise, select QC "
                    "Hold or inventory location.", "", "", ""),
        ("5.3.32.", "Click “Process”.", "", "", ""),
        ("5.3.33.", "Click “OK,” then enter the close date on the MRR and save the form. This completes the MRR "
                    "process in Syteline.", "", "", ""),
        ("h", "5.4. TRR (Streamline) Processing"),
        ("5.4.1.", "For Open the “Create Quality Control Topics” form.", "", "", ""),
        ("5.4.2.", "Select “Production” from the initial topic drop-down.", "", "", ""),
        ("5.4.3.", "Enter the employee who made the error in “Reported By,” along with department, top-level "
                   "item number, and work center.", "", "", ""),
        ("5.4.4.", "In the notes, at minimum state: who made the error, affected assembly, job number, and "
                   "specific details of the error. Then click “Process.”", "", "", ""),
        ("5.4.5.", "Record the topic number from the new tab, close it, and navigate to that topic in “Quality "
                   "Control Topics.”", "", "", ""),
        ("5.4.6.", "Select “X-Ref TRR” and record the generated TRR number.", "", "", ""),
        ("5.4.7.", "Open the TRR form and navigate to the recorded number.", "", "", ""),
        ("5.4.8.", "Set status to “Closed,” reason code to “STRMLINE,” re-enter the original note details in the "
                   "description block, check “Close TRR,” and save. This completes the TRR.", "", "", ""),
        ("h", "5.5. CMR Processing"),
        ("5.5.1.", "For all other discrepancies defined as CMRs, open the “eCMRs” form and click “New.” The CMR "
                   "number (CMR Num, e.g. CMR-260929-111742) is assigned automatically.", "changed",
         "For all other discrepancies defined as CMRs, navigate to “Create Change Request.”",
         "CMRs are created on the eCMRs form; there is no separate Create Change Request form."),
        ("5.5.2.", "Select the “Initial Change,” enter “Reported By,” and select the item number (if "
                   "applicable). Provide a full description of the issue or request in “Requested Action.” The "
                   "Requirement check boxes are set from the Initial Change. Leave all other fields blank.",
         "changed",
         "Enter initial change reason code, “Reported By,” and item number (if applicable). Provide a full "
         "description of the issue or request. Leave all other fields blank.",
         "Names the eCMRs fields. The Requirement check boxes are ticked automatically from Initial Change."),
        ("5.5.3.", "Save the form and record the CMR number.", "changed",
         "Click “Process,” close the new tab, click “OK” on the pop-up, record the change number, and "
         "navigate to “Change Request Management.”",
         "No Process step, change number or second form: the CMR is one record, numbered on New."),
        ("5.5.4.", "Do not enter additional fields at this time.", "changed",
         "On the Change Request form, do not enter additional fields.",
         "There is no separate Change Request form."),
        ("5.5.4.1.", "Set the Priority Field to one of the following (based on need by date)", "changed",
         "If priority is required for processing, change Priority Field to one of the following (based on "
         "need by date)",
         "The eCMRs Priority field has no default, so it is always set."),
        ("5.5.4.1.1.", "High (Priority 1).  Select if ships or needs that day.", "changed",
         "Priority 1, High.  Select if ships or needs that day.",
         "The eCMRs drop-down lists High, Medium, Low."),
        ("5.5.4.1.2.", "Medium (Priority 2).  Select if ships or needed within 24 hours.", "changed",
         "Priority 2, Medium.  Select if ships or needed within 24 hours.",
         "The eCMRs drop-down lists High, Medium, Low."),
        ("5.5.4.1.3.", "Low (Priority 3), for all others.  Expected processing time within the week.", "changed",
         "Priority 3 Low (default), for all others.  Expected processing time within the week.",
         "The eCMRs drop-down lists High, Medium, Low; Low is not filled in by default."),
        ("5.5.4.2.", "", "removed",
         "Click “X-Ref CMR,” record the CMR number, and navigate to that CMR.",
         "Not needed: the change request and the CMR are the same eCMRs record."),
        ("5.5.5.", "Complete all available fields.  Attach any support documentation within IDM of CMR record. "
                   "Set the Quality Reviewer ID (Quality section) as the Quality team member who will work CMR "
                   "to completion with the assistance of Engineering.  Save form.  Assign to Manufacturing "
                   "Engineering (Assigned Field) for review and remarks.", "changed",
         "Complete all available fields.  Attach any support documentation within IDM of CMR record. Set the "
         "Quality reviewer as the Quality team member who will work CMR to completion with the assistance of "
         "Engineering.  Save form.  Assign to Manufacturing Engineering (Assigned Field) for review and remarks.",
         "Names the eCMRs field: Reviewer ID in the Quality section (the name fills in)."),
        ("5.5.6.", "On Build Record, enter the CMR number for traceability within the Notes section at the end.",
         "", "", ""),
        ("5.5.7.", "Engineering will review, determine the CMR solution and load supporting documentation to IDM "
                   "within CMR record (if applicable). Once complete, reassign to Quality and change status to "
                   "“QC Approval.”", "", "", ""),
        ("5.5.8.", "Review data for accuracy. If an NEI or TS was generated and attached in IDM, review and sign "
                   "if approved.  Replace existing copy with signed copy within IDM in CMR record.", "", "", ""),
        ("5.5.9.", "Route the CMR through all departments listed in the Implementation section.", "", "", ""),
        ("5.5.9.1.", "Planning, if communication is required to the floor.  Planning will distribute "
                     "documentation/information to the floor.", "", "", ""),
        ("5.5.9.2.", "Purchasing, if the deviation is a Supplier Deviation Request.  Purchasing will provide "
                     "copies of documentation to the Supplier.", "", "", ""),
        ("5.5.9.3.", "CM, if an NEI or ECO was generated, CMR will be reassigned to Configuration Management and "
                     "will be released into Drawing Books.", "", "", ""),
        ("5.5.9.4.", "After completion of activity (select check box and select yourself as Reviewer ID), CMR "
                     "will need to be reassigned back to Quality (Status to QC Approval and Assigned to QC team "
                     "member identified within Quality section).  Once assigned, Click Notify to send email to "
                     "the Assigned.", "changed",
         "After completion of activity (select check box and select yourself as Reviewer), CMR will need to be "
         "reassigned back to Quality (Status to QC Approval and Assigned to QC team member identified within "
         "Quality section).  Once assigned, Click Notify to send email to the Assigned.",
         "Names the eCMRs field: Reviewer ID (the name fills in)."),
        ("5.5.9.5.", "If a department is not required, select corresponding check box, indicating implementation "
                     "is complete for that department (in this instance, not required).", "", "", ""),
        ("5.5.10.", "After all reviews are complete, check “Closed” (Close Date and Closed By fill in) and change "
                    "status to “Complete.” Save the form. This completes the CMR process.", "changed",
         "After all reviews are complete, check “Closed” and change status to “Completed.” This completes the "
         "CMR process.",
         "The eCMRs Status value is “Complete”; ticking Closed fills Close Date and Closed By."),
        ("5.6.", "If there are additional questions regarding processing MRRs, CMRs, and TRRs, contact the "
                 "Quality Manager (or Designee).", "", "", ""),
    ],
    flowchart=True,
    review=[
        "IDM: steps 5.5.5, 5.5.7 and 5.5.8 attach documents within IDM of the CMR record. The eCMRs form "
        "sends its record to the IDM documents widget like Infor's forms do; confirm on TRN which documents "
        "it shows (the Item's) and how attaching works, before release.",
        "Notify: step 5.5.9.4 emails the Assigned person with the Notify button. In eCMRs, Notify uses the same "
        "Enflite email event as QC CMRs - confirm on TRN that the email arrives before release.",
        "Flowchart (section 6): unchanged; the “Create CMR” box is marked “(eCMRs)” in this draft.",
    ],
)

QA_300_003 = dict(
    key="qa-300-003",
    number="QA-300-003",
    title="Supplier Deviation Request (SDR)",
    rev_old="E", issued_old="07/07/2026",
    rev_new="F (draft)",
    summary="Step 5.5 names the eCMRs form. Everything else is unchanged.",
    company_private=False,
    revlog=[
        ("A", "Changed from PUR-300-007 to SQ-300-004; added additional supplier actions in step 3; changed "
              "from Purchasing POC to Supplier Quality POC; updated routing instructions since form is now "
              "electronic; combined former individual rows to consolidate", "07/05/18", "Estep", "Nel",
         "Schilling", "N/A"),
        ("B", "Changed Document Number from “SQ-300-004” to “QA-300-003”.Removed references to “LifePort” "
              "throughout. Changed Refer Documents from “SQ” to “QC” and Roster “-544” to “-044”. Removed "
              "Definitions “EGL”, “SQ” and “QCL”. Removed LifePort GRP and references to SQ Rep in section 5. "
              "Removed section 6.", "3/22/19", "G Stetler", "J Nabe&T Arguelles", "G Stetler", "G Stetler"),
        ("C", "Corrected references to Tech Help Work Instructions, ENG-310-301.", "07/17/19", "G Stetler",
         "J Nabe", "G Stetler", "G Stetler"),
        ("D", "Corrected Performed By to align with current practices (Step 19).  Update format of SDR file "
              "naming (step 9).", "8/17/2023", "J Nabe", "E Laney", "J Nabe", "J Nabe"),
        ("E", "Updated procedure to incorporate usage of Syteline CMR’s; changes throughout.", "7/6/2026",
         "J Nabe", "E Laney", "J Nabe", "J Nabe"),
        ("F", "Step 5.5: SDRs are entered in the eCMRs form (replaces the former CMR forms).", "Draft",
         "", "", "", ""),
    ],
    scope="This work instruction applies to Enflite. The Supplier Deviation Request work instruction does not "
          "cover the requirements of the Tech Help Work Instruction (ENG-310-301).\n"
          "Department: Quality, Purchasing and Engineering\n"
          "Job Position:  Quality Control, Buyer and Designated Engineer",
    purpose="This work instruction defines the process for suppliers to document any departure from drawing, "
            "specification, or other purchase order requirement and request disposition from Enflite. This "
            "policy supports the requirements of ISO 9001 and AS9100, as applicable.",
    references=[
        ("QA-300-037", "MRR, CMR AND TRR PROCESSING"),
        ("QA-400-005", "SUPPLIER DEVIATION REQUEST"),
        ("QA-400-044", "AUTHORITY AND ROSTER OF AUTHORIZED PERSONNEL"),
    ],
    definitions=[(a, b, "", "", "") for a, b in [
        ("BUYER", "Purchasing Agent"), ("PO", "Purchase Order"), ("ECO", "Engineering Change Order"),
        ("MRB", "Material Review Board"), ("NEI", "Notice of Engineering Intent"), ("QC", "Quality Control"),
        ("SDR", "Supplier Deviation Request"), ("TRR", "Topic Review Request"), ("TS", "Temporary Solution")]],
    procedure_title="5. WORK INSTRUCTION",
    procedure=[
        ("5.1.", "If a supplier has departed from drawing, specification, or other purchase order requirement "
                 "with physical product (oversized hole, undersized length) that cannot be reworked to blueprint "
                 "requirements, they shall fill out the supplier section of the Supplier Deviation Request, "
                 "QA-400-005.", "", "", ""),
        ("5.2.", "If a supplier has a question on a drawing because of missing or incomplete information "
                 "(dimensions, radius, material, etc.) or the part cannot be manufactured from the information "
                 "given on the drawing, QA-400-005 may also be used for this purpose.", "", "", ""),
        ("5.3.", "The Supplier shall fill out the Supplier Section of the form, which includes Supplier Name, "
                 "PO#, Part Number, Part Revision, Quantity, SDR Request Date, PO Promise Date, Requestor, "
                 "Phone, and Email. A brief description of the deviation (or clarification) shall also be "
                 "included, along with the requested action.", "", "", ""),
        ("5.4.", "Once the supplier has filled out the form, they shall submit it via email to Enflite "
                 "SDR@enflite.com", "", "", ""),
        ("5.5.", "The SDR received from the supplier will be entered into Syteline via the eCMRs form.  For "
                 "further details, please refer to QA-300-037 MRR, CMR, and TRR Processing.", "changed",
         "The SDR received from the supplier will be entered into Syteline via CMR form.  For further details, "
         "please refer to QA-300-037 MRR, CMR, and TRR Processing.",
         "CMRs are now entered on the eCMRs form."),
        ("5.6.", "The SDR form will be saved into IDM in Syteline under the CMR number.", "", "", ""),
        ("5.7.", "If Enflite requires additional information to address issue, the Supplier will be notified by "
                 "Manufacturing Engineering requesting further details.", "", "", ""),
        ("5.8.", "If the supplier makes the decision to ship the article without receiving the signed SDR, they "
                 "are doing so at their own risk and article may be rejected.", "", "", ""),
        ("5.9.", "Manufacturing Engineering shall monitor activities within Syteline regarding CMR’s for newly "
                 "entered SDRs.  Engineering Representative will review issue and complete the disposition.  Upon "
                 "completion, Engineering will notify Quality for further processing.", "", "", ""),
        ("5.9.1.", "The Engineering Representative shall be defined by the MRB Authority Roster, QA-400-044.",
         "", "", ""),
        ("5.10.", "Quality will complete remaining items on SDR form and the approved form will be sent to "
                  "Purchasing who will email the completed form and supporting documentation (such as drawings, "
                  "ECO, NEI, or TS), if applicable, back to the supplier.", "", "", ""),
        ("5.11.", "The Buyer is responsible for adding comments, if required, to the PO showing the details of "
                  "the SDR.", "", "", ""),
        ("5.12.", "The Supplier must reference the SDR number on the packing list where applicable and attach a "
                  "copy of the completed and approved SDR with the articles paperwork.", "", "", ""),
        ("5.13.", "A copy of the approved Supplier Deviation Request must accompany the article(s) shipment or "
                  "the article(s) may be returned to the supplier at the supplier’s expense.", "", "", ""),
    ],
    flowchart=False,
    review=[
        "IDM: step 5.6 saves the SDR form into IDM under the CMR number. Attaching IDM documents to an eCMRs "
        "record has not been tested yet - confirm on TRN before release.",
        "Optional, not changed: when entering an SDR in eCMRs, the SDR's Supplier Name, PO#, Part Number, Part "
        "Revision and Quantity go in Vendor, PO Num, Item, Drawing Revision and Qty; the description and "
        "requested action go in Requested Action.",
    ],
)

PROCEDURES = [QA_300_037, QA_300_003]
